version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_hw
    restart: always
    environment:
      POSTGRES_USER: hw-03-user
      POSTGRES_PASSWORD: 25525522
      POSTGRES_DB: hw-03-db
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data